import './globals.css'
import Navbar from "@/components/Navbar.jsx";

export const metadata = {
  title: 'Second Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        <main className="container mx-auto flex justify-center items-center h-[calc(100vh-4rem)]">
          {children}
        </main>
      </body>
    </html>
  )
};