import './globals.css'

export const metadata = {
  title: 'Second Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto flex justify-center items-center h-screen">{children}</body>
    </html>
  )
};